---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      vagrantfile_erb: Vagrantfile.erb
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8080}]

suites:
  - name: default
    run_list:
      - recipe[simple-web::default]
    attributes:
