AllCops:
  Exclude:
    - vendor/**
    - metadata.rb
    - tmp/**/*

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
SingleSpaceBeforeFirstArg:
  Enabled: false
Style/FileName:
  Enabled: false
Style/WordArray:
  Enabled: false
